Recipe:
  type: object
  required:
    - _id
    - name
    - ingredients
    - description
    - userId
    - userName
    - createdAt
    - grade
    - macros
    - totalCalories
  properties:
    _id:
      type: string
      example: "abcdef1234567890abcdef12"
    name:
      type: string
      example: "Pasta al Pesto"
    ingredients:
      type: array
      items:
        $ref: './foodItem.yml'
    description:
      type: string
      example: "A classic Italian pasta recipe with fresh basil pesto."
    userId:
      type: string
      example: "1234567890abcdef12"
    userName:
      type: string
      example: "mario.rossi"
    createdAt:
      type: string
      format: date-time
      example: "2024-01-15T10:30:00Z"
    grade:
      type: string
      example: "A"
    macros:
      type: array
      items:
        $ref: './nutrient.yml'
    totalCalories:
      type: number
      example: 650
    recipeRating:
      $ref: './recipeRating.yml'
